#DiscordSRVUtils addon config:


#Recommended version for the server
version: "1.16"




#Should we send you that there is an update when you join the server?
update_checker: true



#welcomer_channel. This channel will contain welcome message for people who join the discord server
welcomer_channel: 000000000000000000

welcomer_ignore_bots: true
#welcomer_message. We will send this message when a discord user joins
#Avaiable PlaceHolders: [User_Name], [User_Tag], [User_Mention].
welcomer_message:
  - "🔸 **Welcome [User_Name] To The server!**"
  - ""
  - ""
  - "🔸 **Server ip** | play.example.com"
  - ""
  - ""
  - "🔸 **Store** | store.example.com"

#mc_welcomer_message. This message will be send to online players when a new member joins the discord server
#Avaible PlaceHolders: [User_name], [User_Tag], [Guild_Name].
mc_welcomer_message: "&b[User_Name] &aJoined the Discord server"

#Should we send the message above to all players when a new member joins the discord server?
#Set to true if you want the message to be send, false if you dont
join_message_to_online_players: true

#What is the embed color we should use for the welcomer embed?
#Default: RED
welcomer_message_embed_color: RED

#Should we send the afk messages to discord?
essentials_afk_to_discord: true

#Message to be send when player is afk
#Avaible PlaceHolders: [Player_Name], [Player_DisplayName]
#PlaceholderAPI is supported.
essentials_player_afk_message:
  - "**[Player_Name] is now afk**"

#Message to send when player is no longer afk
#Avaible PlaceHolders: [Player_Name], [Player_DisplayName]
#PlaceholderAPI is supported.
essentials_player_no_longer_afk_message:
  - "**[Player_Name] is no longer afk**"
